import db from './db.js';
import { cryptoRandomString } from './utils.js';

export const defaultMissions = [
  // Mots Faciles (30)
  { category: 'Mots Faciles', description: 'Chocolat' },
  { category: 'Mots Faciles', description: 'Soleil' },
  { category: 'Mots Faciles', description: 'Vacances' },
  { category: 'Mots Faciles', description: 'Musique' },
  { category: 'Mots Faciles', description: 'Café' },
  { category: 'Mots Faciles', description: 'Pizza' },
  { category: 'Mots Faciles', description: 'Chapeau' },
  { category: 'Mots Faciles', description: 'Avion' },
  { category: 'Mots Faciles', description: 'Gâteau' },
  { category: 'Mots Faciles', description: 'Valise' },
  { category: 'Mots Faciles', description: 'Montagne' },
  { category: 'Mots Faciles', description: 'Plage' },
  { category: 'Mots Faciles', description: 'Cinéma' },
  { category: 'Mots Faciles', description: 'Chien' },
  { category: 'Mots Faciles', description: 'Chat' },
  { category: 'Mots Faciles', description: 'Voiture' },
  { category: 'Mots Faciles', description: 'Bouteille' },
  { category: 'Mots Faciles', description: 'Livre' },
  { category: 'Mots Faciles', description: 'Maison' },
  { category: 'Mots Faciles', description: 'Jardin' },
  { category: 'Mots Faciles', description: 'Miroir' },
  { category: 'Mots Faciles', description: 'Fête' },
  { category: 'Mots Faciles', description: 'Cadeau' },
  { category: 'Mots Faciles', description: 'Chanson' },
  { category: 'Mots Faciles', description: 'Étoile' },
  { category: 'Mots Faciles', description: 'Bateau' },
  { category: 'Mots Faciles', description: 'Fraise' },
  { category: 'Mots Faciles', description: 'Pomme' },
  { category: 'Mots Faciles', description: 'Glace' },
  { category: 'Mots Faciles', description: 'Soupe' },

  // Mots Courants (30)
  { category: 'Mots Courants', description: 'Parapluie' },
  { category: 'Mots Courants', description: 'Guitare' },
  { category: 'Mots Courants', description: 'Cravate' },
  { category: 'Mots Courants', description: 'Croissant' },
  { category: 'Mots Courants', description: 'Téléphone' },
  { category: 'Mots Courants', description: 'Chaussette' },
  { category: 'Mots Courants', description: 'Bicyclette' },
  { category: 'Mots Courants', description: 'Fromage' },
  { category: 'Mots Courants', description: 'Trompette' },
  { category: 'Mots Courants', description: 'Coussin' },
  { category: 'Mots Courants', description: 'Brioche' },
  { category: 'Mots Courants', description: 'Pantoufle' },
  { category: 'Mots Courants', description: 'Horloge' },
  { category: 'Mots Courants', description: 'Serviette' },
  { category: 'Mots Courants', description: 'Pinceau' },
  { category: 'Mots Courants', description: 'Lanterne' },
  { category: 'Mots Courants', description: 'Toboggan' },
  { category: 'Mots Courants', description: 'Baguette' },
  { category: 'Mots Courants', description: 'Escrime' },
  { category: 'Mots Courants', description: 'Camping' },
  { category: 'Mots Courants', description: 'Carnet' },
  { category: 'Mots Courants', description: 'Pharmacie' },
  { category: 'Mots Courants', description: 'Biscuits' },
  { category: 'Mots Courants', description: 'Écharpe' },
  { category: 'Mots Courants', description: 'Jumelles' },
  { category: 'Mots Courants', description: 'Moustique' },
  { category: 'Mots Courants', description: 'Casquette' },
  { category: 'Mots Courants', description: 'Casserole' },
  { category: 'Mots Courants', description: 'Compas' },
  { category: 'Mots Courants', description: 'Tournesol' },

  // Mots Insolites (35)
  { category: 'Mots Insolites', description: 'Astronaute' },
  { category: 'Mots Insolites', description: 'Hippopotame' },
  { category: 'Mots Insolites', description: 'Caméléon' },
  { category: 'Mots Insolites', description: 'Aquarium' },
  { category: 'Mots Insolites', description: 'Papillon' },
  { category: 'Mots Insolites', description: 'Kangourou' },
  { category: 'Mots Insolites', description: 'Tornade' },
  { category: 'Mots Insolites', description: 'Soucoupe' },
  { category: 'Mots Insolites', description: 'Dinosaure' },
  { category: 'Mots Insolites', description: 'Sorcier' },
  { category: 'Mots Insolites', description: 'Trombone' },
  { category: 'Mots Insolites', description: 'Catapulte' },
  { category: 'Mots Insolites', description: 'Labyrinthe' },
  { category: 'Mots Insolites', description: 'Perroquet' },
  { category: 'Mots Insolites', description: 'Pharaon' },
  { category: 'Mots Insolites', description: 'Licorne' },
  { category: 'Mots Insolites', description: 'Boomerang' },
  { category: 'Mots Insolites', description: 'Hamac' },
  { category: 'Mots Insolites', description: 'Vampire' },
  { category: 'Mots Insolites', description: 'Pyramide' },
  { category: 'Mots Insolites', description: 'Gondole' },
  { category: 'Mots Insolites', description: 'Saxophone' },
  { category: 'Mots Insolites', description: 'Tarentule' },
  { category: 'Mots Insolites', description: 'Mongolfière' },
  { category: 'Mots Insolites', description: 'Mammouth' },
  { category: 'Mots Insolites', description: 'Submersible' },
  { category: 'Mots Insolites', description: 'Manchot' },
  { category: 'Mots Insolites', description: 'Flamant' },
  { category: 'Mots Insolites', description: 'Orang-outan' },
  { category: 'Mots Insolites', description: 'Cactus' },
  { category: 'Mots Insolites', description: 'Chameau' },
  { category: 'Mots Insolites', description: 'Dragon' },
  { category: 'Mots Insolites', description: 'Volcan' },
  { category: 'Mots Insolites', description: 'Caravane' },
  { category: 'Mots Insolites', description: 'Youkoulélé' },

  // Mots Difficiles (30)
  { category: 'Mots Difficiles', description: 'Ananas' },
  { category: 'Mots Difficiles', description: 'Archipel' },
  { category: 'Mots Difficiles', description: 'Constellation' },
  { category: 'Mots Difficiles', description: 'Kaleidoscope' },
  { category: 'Mots Difficiles', description: 'Symphonie' },
  { category: 'Mots Difficiles', description: 'Microscope' },
  { category: 'Mots Difficiles', description: 'Boussole' },
  { category: 'Mots Difficiles', description: 'Pronom' },
  { category: 'Mots Difficiles', description: 'Amulette' },
  { category: 'Mots Difficiles', description: 'Stalactite' },
  { category: 'Mots Difficiles', description: 'Télescope' },
  { category: 'Mots Difficiles', description: 'Protocole' },
  { category: 'Mots Difficiles', description: 'Alchimiste' },
  { category: 'Mots Difficiles', description: 'Metronome' },
  { category: 'Mots Difficiles', description: 'Diapason' },
  { category: 'Mots Difficiles', description: 'Carrousel' },
  { category: 'Mots Difficiles', description: 'Flibustier' },
  { category: 'Mots Difficiles', description: 'Gargouille' },
  { category: 'Mots Difficiles', description: 'Hélicoptère' },
  { category: 'Mots Difficiles', description: 'Sphinx' },
  { category: 'Mots Difficiles', description: 'Topinambour' },
  { category: 'Mots Difficiles', description: 'Centaure' },
  { category: 'Mots Difficiles', description: 'Clepsydre' },
  { category: 'Mots Difficiles', description: 'Particule' },
  { category: 'Mots Difficiles', description: 'Sarcophage' },
  { category: 'Mots Difficiles', description: 'Ampoule' },
  { category: 'Mots Difficiles', description: 'Gros-mot' },
  { category: 'Mots Difficiles', description: 'Clavecin' },
  { category: 'Mots Difficiles', description: 'Théâtre' },
  { category: 'Mots Difficiles', description: 'Girafe' }
];

export function seedDefaultMissions() {
  db.prepare('DELETE FROM missions WHERE game_id IS NULL AND is_custom = 0').run();

  const insert = db.prepare('INSERT INTO missions (id, game_id, category, description, is_custom) VALUES (?, NULL, ?, ?, 0)');
  const insertMany = db.transaction((missions) => {
    for (const m of missions) {
      insert.run(cryptoRandomString(), m.category, m.description);
    }
  });
  insertMany(defaultMissions);
  console.log(`🎯 ${defaultMissions.length} mots uniques par défaut ajoutés au pool.`);
}
